defaults:
  - logger: mlflow
  - data: single_image
  - method: lookahead
  - metric: pure_score
  - model: resnet50
  - classes: imagenet
  - replacement: mean_color
  - segmentation: hexagonal
  - _self_

# Explainer hyperparameters
target_class_idx: null
max_regions: 1
desired_length: 30
batch_size: 64
