name: Python Lint (RationAI Standard)
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_python-lint-impl.yml
